
version: '3.8'

services:
  # Frontend React/Vite
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - REACT_APP_ETL_URL=http://etl:8001
    depends_on:
      - backend
    networks:
      - ch-network
    restart: unless-stopped

  # Backend API IA
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:@mysql:3306/dwh
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
    volumes:
      - ../fast-api/API/models:/app/API/models
    networks:
      - ch-network
    restart: unless-stopped

  # Base de données MySQL
  mysql:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dwh
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
      - ../docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ch-network
    restart: unless-stopped

  # Service ETL
  etl:
    build:
      context: ..
      dockerfile: docker/Dockerfile.etl
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+pymysql://root:@mysql:3306/dwh
    depends_on:
      - mysql
    networks:
      - ch-network
    restart: unless-stopped

  # Redis pour cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ch-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  ch-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
