
apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: dwh
    user: root
    password: ""
    isDefault: true
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timezone: "UTC"
    secureJsonData: {}
    version: 1
    editable: true
